version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
      args:
        VITE_API_BASE_URL: "http://localhost:8080"
    ports:
      - "5173:5173"
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URL=postgres://postgres:password@postgres:5432/task-tracker
      - REDIS_CONNECTION_STRING=redis://redis:6379
    depends_on:
      - mongo
      - redis
    networks:
      - app-network

  mongo:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=task-tracker
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:6
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
